### ISSUE TITLE
error on calculix example

### ISSUE THREAD

**Issue by berndhahnebach** [xcfem/xc_examples#1]
I get an error  ... might be a typo ... on commit 7e809d8

```
$ python cantilever_mesh_generation.py 
Traceback (most recent call last):
  File "cantilever_mesh_generation.py", line 61, in <module>
    seedElemHandler.defaultTransformation= lin.name #Orientation of the element axis.
AttributeError: 'LinearCrdTransf3d' object has no attribute 'name'
$ 
```

bernd

**Comment by berndhahnebach** [comment]
https://github.com/xcfem/xc_examples/blob/7e809d8ade1352e3116f2f36869f475368b30ca3/calculix_cantilever_example/cantilever_mesh_generation.py#L61

**Comment by lcpt** [comment]
> [xc_examples/calculix_cantilever_example/cantilever_mesh_generation.py](https://github.com/xcfem/xc_examples/blob/7e809d8ade1352e3116f2f36869f475368b30ca3/calculix_cantilever_example/cantilever_mesh_generation.py#L61)
> 
> Line 61 in [7e809d8](/xcfem/xc_examples/commit/7e809d8ade1352e3116f2f36869f475368b30ca3)
>  seedElemHandler.defaultTransformation= lin.name #Orientation of the element axis.

By the way, how do you quote the code like in your comment?

**Comment by berndhahnebach** [comment]
```
$ python cantilever_mesh_generation.py 
deltaY=  0.0877720135714
$
```

:-)

**Comment by berndhahnebach** [comment]
just klick on a line in github, the line will be yellow in browser. Copy the browser address, paste the address here, github will recognize it and do the rest for you ...

`
https://github.com/xcfem/xc_examples/blob/7e809d8ade1352e3116f2f36869f475368b30ca3/calculix_cantilever_example/cantilever_mesh_generation.py#L86
`

will be 

https://github.com/xcfem/xc_examples/blob/7e809d8ade1352e3116f2f36869f475368b30ca3/calculix_cantilever_example/cantilever_mesh_generation.py#L86

**Comment by berndhahnebach** [comment]
`
$ python display_loads.py 
Traceback (most recent call last):
  File "display_loads.py", line 4, in <module>
    from postprocess.xcVtk import vtk_graphic_base
ImportError: cannot import name vtk_graphic_base
hugo@ahorn:~/Documents/projekte--BIM--opendev/xc/xc_examples/calculix_cantilever_example$ python display_blocks.py 
`

**Comment by berndhahnebach** [comment]
BTW: with shift you can mark more than one line in github code view ...

`
https://github.com/xcfem/xc_examples/blob/7e809d8ade1352e3116f2f36869f475368b30ca3/calculix_cantilever_example/cantilever_mesh_generation.py#L77-L86
`

https://github.com/xcfem/xc_examples/blob/7e809d8ade1352e3116f2f36869f475368b30ca3/calculix_cantilever_example/cantilever_mesh_generation.py#L77-L86

**Comment by lcpt** [comment]
> next error on display_blocks.py and display_loads.py and display_diagram.py
> 
> `$ python display_loads.py Traceback (most recent call last): File "display_loads.py", line 4, in <module> from postprocess.xcVtk import vtk_graphic_base ImportError: cannot import name vtk_graphic_base $`

Thank you for the "tutorial" about the insertion of the code in the comments. Nice explanation!

About the error: have you updated Python modules (sh local_install.sh)?

**Comment by berndhahnebach** [comment]
example:

`
$ grep -r vtk_CAD_graphic.pyc
xc/python_modules/installed_files_history.txt:/usr/local/lib/python2.7/dist-packages/postprocess/xcVtk/CAD_model/vtk_CAD_graphic.pyc
$
`
and 

`
$ find /usr/local -name "vtk_CAD_graphic.pyc"
/usr/local/lib/python2.7/dist-packages/postprocess/xcVtk/CAD_model/vtk_CAD_graphic.pyc
$
`

but for vtk_graphic_base.pyc


`
$ grep -r vtk_graphic_base.pyc
xc/python_modules/installed_files_history.txt:/usr/local/lib/python2.7/dist-packages/postprocess/xcVtk/vtk_graphic_base.pyc
$ 
`

should be installed but 
`
$ find /usr/local -name "vtk_grafico_base.pyc"
/usr/local/lib/python2.7/dist-packages/postprocess/xcVtk/vtk_grafico_base.pyc
$ 
`

double checked with the file manager, it is not there ... but I have compiled and installed latest xc. I will double check installation another time ...

**Comment by berndhahnebach** [comment]
it was my installation ... 

![screenshot_20181114_064618](https://user-images.githubusercontent.com/6129869/48462593-0ace1e80-e7d9-11e8-8114-9d0c913b97ec.png)

**Comment by berndhahnebach** [comment]
https://github.com/xcfem/xc_examples/commit/a37d301dface2d6acfc729336fb137269e1a7990

**Comment by berndhahnebach** [comment]
just for myself ...

9000 kN x 8 m = 72000 kNm = 7.20E4 kNm
th minus is because the force points upwards, and thus creates a negative bending moment
