### ISSUE TITLE
calculix cantilever in 2D

### ISSUE THREAD

**Issue by berndhahnebach** [xcfem/xc_examples#2]
https://github.com/berndhahnebach/xc_examples/blob/21e0dcd8179517b9f6a764d38c4aea90c543e5f7/calculix_cantilever_2D/cantilever_mesh_generation.py

tried the calculix cantilever in 2D but failed to create a surface or face for meshing shell elements ...

**Comment by berndhahnebach** [comment]
https://github.com/berndhahnebach/xc_examples/blob/master/calculix_cantilever_example/cantilever_mesh_generation.py

**Comment by berndhahnebach** [comment]
found something 

https://github.com/berndhahnebach/XCmodels/blob/master/ps_bole_calculs_statiques/xc_model_impact/model_data.py#L41-L42

**Comment by berndhahnebach** [comment]
here is where I stuck ... 

https://github.com/berndhahnebach/xc_examples/blob/calculix2D/calculix_cantilever_2D/cantilever_mesh_generation.py#L51-L52

**Comment by lcpt** [comment]
Meanwhile you can take a look here:

https://github.com/xcfem/xc/blob/master/verif/tests/elements/shell/test_shell_mitc4_04.py

The syntax is a bit outdated it works anyway) but you can see how to define the material for the shell elements, how to define the seed element (the template element that will be put in the mesh) and how to create the mesh.

**Comment by berndhahnebach** [comment]
> Meanwhile you can take a look here:
> 
> https://github.com/xcfem/xc/blob/master/verif/tests/elements/shell/test_shell_mitc4_04.py

great this will help a lot. I will give it a try and report back if I run into trouble again ...

BTW: Is ist possible to display the FEM mesh element and FEM mesh nodes too? For example on anas working model example? See https://github.com/anaiortega/XCmodels/blob/master/workingModel/display/display_mesh.py

**Comment by lcpt** [comment]
I've taken your example and modified it to fulfill some of your suggestions in the cormments.

The code was correct but there was an error on the line that came from the 1D example:

> https://github.com/xcfem/xc_examples/blob/ecdba810a0d578300a459f31635d0d85e2a1aac3/calculix_cantilever_example_1D/cantilever_mesh_generation.py#L90
This line is wrong. I load the node who has the same tag that pt1 not the node "at" pt1.

I've replaced pt1.tag by pt1.getNode().tag

Thats why the results were "erratic".

I have named this example calculix_cantilever_example_2D to avoid a conflict with your fork (we can discuss how to solve this kind of conflicts later).

To make things work you must pull XC again (i've added the displayLocalAxes method to the RecordDefDisplayEF class.

Cheers Luis.

**Comment by lcpt** [comment]
I've added display_mesh.py and display_localAxes to both examples. So you can see the mesh and the element axed. To see a "wireframe" image you can press "w".

**Comment by berndhahnebach** [comment]
very cool stuff luis :-)

I used the element with in element plane load. With this it needs really a lot element to come close to the 87 mm. i would have expected to need much less of quadratic quad element ...

see https://github.com/berndhahnebach/xc_examples/blob/calculix2D/calculix_cantilever_example_2D/cantilever_mesh_generation.py and commit on top of yours https://github.com/berndhahnebach/xc_examples/commit/43eef0e598b90fc44d481548331c228c551c2f1a#diff-2c847164bb6c61d02bc9e4a50a55b661

**Comment by berndhahnebach** [comment]
> I have named this example calculix_cantilever_example_2D to avoid a conflict with your fork (we can discuss how to solve this kind of conflicts later).


IMHO you would not need to do anything in this regard. This is what is git and branches is for.

**Comment by berndhahnebach** [comment]
Just as an example. With CCX and ten 6 nod triangle element I get a z-deflection of 86.5 mm in plane load. 
![screenshot_20181126_021313](https://user-images.githubusercontent.com/6129869/48987629-fe26c000-f120-11e8-9a45-b706e665a20e.png)

**Comment by berndhahnebach** [comment]
eight 8 node quad give 87.2 mm in ccx. 


![screenshot_20181126_041043](https://user-images.githubusercontent.com/6129869/48991133-e9065d00-f131-11e8-99a7-69a2ce4133b8.png)

**Comment by lcpt** [comment]
They are four node shell elements.
Are you trying to teach me a lesson?

Regards Luis.

**Comment by berndhahnebach** [comment]
> They are four node shell elements.
> Are you trying to teach me a lesson?

For sure not Luis! I try to understand the results myself and I played a bit yesterday. Since I like to keep such findings somehow I just posted them here. 

BTW: It is the other way around. Would it be possible to teach me in this regard?

As far as I understand XC uses this element http://opensees.berkeley.edu/wiki/index.php/Shell_Element  
This seam to be a four node shell element with bilinear approximation. I have no idea how it is possible to make a bilinear approximation by four nodes. I thought for a bilinear approximation with a quad element  eight nodes are needed by definition ?!?

I only know CalculiX ccx. In CalculiX a four node shell element has linear approximation and a 8 node shell element has bilinear approximation. http://feacluster.com/CalculiX/ccx_2.13/doc/ccx/node36.html and http://feacluster.com/CalculiX/ccx_2.13/doc/ccx/node38.html

cheers bernd

**Comment by berndhahnebach** [comment]
EDIT: damn I mixed up quadratic and bilinear ... Some part of the text above is rubbish ...  

> They are four node shell elements.

As far as I understand XC uses this element http://opensees.berkeley.edu/wiki/index.php/Shell_Element  
This seam to be a four node shell element with bilinear approximation, no quadratic approximation?!


> We can also add MITC9 and other shell elements from the OpenSees repository. I'm particularly interested in the geometrically nonlinear elements but that is another [issue](https://github.com/xcfem/xc/issues/11)  Does it mean ATM XC does not support any other shell element than the bilinear quad shell?

cheers bernd

**Comment by lcpt** [comment]
Yeah, for now we have only the MITC4. 

If you need the MITC9 element, the porting of the code into XC is almost done but I must adapt the meshing algorithms too and write some tests. It will take me some time to do that.

Well, maybe it's the right time to do this...

Cheers Luis.

**Comment by lcpt** [comment]
On second thought, I think you're right. This task has already waited far too long.

I'll write the code as soon as possible. The use of small MITC4 elements is not very elegant.

Cheers.

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/50171478-d88d7080-02f2-11e9-82fa-307721186b5a.png)

Eight MITC9 (nine node shell elements) give 88.2 mm. I'll upload the code right now.

**Comment by anaiortega** [comment]
Bravo !!!

**Comment by lcpt** [comment]
I've pushed the code.

There are some minor problems to solve when meshing with elements that have mid-side nodes but this is another issue.

Cheers Luis.
