### ISSUE TITLE
Exporting a Mesh to an ASCII format, preferably in gmsh format. 

### ISSUE THREAD

**Issue by lokitkhemka** [xcfem/xc_examples#6]
I am curious if there is any way to export a Finite Element Mesh to a `gmsh` native format for reading it using code? For example, I want to export the mesh of `slope_stability_analysis_example_01.py` example so that I can read it elsewhere, how can I modify that example? I could not find anything in the examples, but if there is one please point it out to me.

Thank you.

**Comment by lcpt** [comment]
This is more a discussion than an issue, don't you think?

There is no predefined way to export the mesh to gmsh. Nevertheless, it's quite straightforward to iterate through the nodes and elements and write the coordinates and node tags to a gmsh file. It will be something like (be careful, I have not checked the code):

```
f= open('xxx', w)

xcTotalSet= modelSpace.getTotalSet()
f.write('nodes\n')
for n in xcTotalSet.nodes:
    pos= n.getInitialPos3d
    f.write(n.tag, pos.x, pos.y, pos.z)
f.wirte('elements\n')
for e in xcTotalSet.elements:
    nodes= e.getNodes.getExternalNodes
    nodeTags= list()
    for n in nodes:
        nodeTags.append(n.tag)
    f.write(e.tag, nodeTags)
```
This could be a rough approximation to the code you're searching for. Of course, there are some work to do concerning the file format etc.

**Comment by lokitkhemka** [comment]
Sorry about that. I am not supergood with github in general. Only thing I know about github is `git add`, `git commit` and `git push`. I am slowly learning more.

**Comment by lokitkhemka** [comment]
Hi, the code worked perfectly. Only change was to add string formatting, which was easy.

Thank you for your help.

**Comment by lcpt** [comment]
> Sorry about that. I am not supergood with github in general. Only thing I know about github is `git add`, `git commit` and `git push`. I am slowly learning more.

No problem.

**Comment by lcpt** [comment]
> Hi, the code worked perfectly. Only change was to add string formatting, which was easy.
> 
> Thank you for your help.

With pleasure.
